#! /bin/sh
#
# Copyright (C) 2011, 2012 Nicira, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
### BEGIN INIT INFO
# Provides:          openvswitch-switch
# Required-Start:    $network $named $remote_fs $syslog
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Open vSwitch switch
# Description:       openvswitch-switch provides the userspace components and utilities for
#                    the Open vSwitch kernel-based switch.
### END INIT INFO

if test "$EUID" != "0"; then
    echo "Please run as root"
    exit 1
fi

export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

OVS_CTL_PATH=/usr/local/share/openvswitch/scripts/ovs-ctl
if test ! -e $OVS_CTL_PATH; then
    OVS_CTL_PATH=/usr/share/openvswitch/scripts/ovs-ctl
    if test ! -e $OVS_CTL_PATH; then
        echo "ovs-ctl missing"
        exit 1
    fi
fi

ovs_ctl () {
    set $OVS_CTL_PATH "$@"
    "$@"
}

load_kmod () {
    ovs_ctl load-kmod || exit $?
}

start () {
    if ovs_ctl load-kmod; then
	:
    else
	    exit 0
    fi
    set ovs_ctl ${1-start} --system-id=random
    "$@" || exit $?
}

stop () {
    ovs_ctl stop
}

case $1 in
    start)
        start
	;;
    stop | force-stop)
        stop
        ;;
    reload | force-reload)
        # The OVS daemons keep up-to-date.
        ;;
    restart)
        stop
        start
        ;;
    status)
        ovs_ctl status
        exit $?
        ;;
    force-reload-kmod)
        start force-reload-kmod
        ;;
    load-kmod)
        load_kmod
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status|force-stop|force-reload-kmod|load-kmod}" >&2
        exit 1
        ;;
esac

exit 0
